version: '3'
services:

  nodejs:
    build:
      context: .
      dockerfile: ./docker/nodejs/Dockerfile
    container_name: "${DOCKER_PREFIX}-nodejs"
    depends_on:
      - app
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www
    networks:
      - app-network

  #PHP Service
  app:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    image: digitalocean.com/php
    user: root
    container_name: "${DOCKER_PREFIX}-app"
    restart: unless-stopped
    tty: true
    depends_on:
      - db
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php-fpm/supervisor-workers.conf:/etc/supervisor/conf.d/supervisor-workers.conf
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: "${DOCKER_PREFIX}-webserver"
    restart: unless-stopped
    tty: true
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:8.0.15
    container_name: "${DOCKER_PREFIX}-db"
    restart: unless-stopped
    tty: true
    command:
      --default-authentication-plugin=mysql_native_password
      --performance-schema --secure-file-priv=""
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  beanstalkd:
    build: ./docker/beanstalkd
    container_name: "${DOCKER_PREFIX}-beanstalkd"
    ports:
      - "11300:11300"
    privileged: true
    depends_on:
      - app
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: "${DOCKER_PREFIX}-mongo"
    restart: unless-stopped
    tty: true
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./docker/mongo/db:/data/db
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
